### ISSUE TITLE
TypeError: unhashable type: 'GPUTensor' after 'make test'

### ISSUE THREAD

**Issue by vsov** [NervanaSystems/nervanagpu#18]
Hello

Running tests just after building of nervanagpu produces the following error:

```
Running unit tests...
nosetests -a '!slow' ""   nervanagpu
E
======================================================================
ERROR: nervanagpu.tests.test_tensor.TestTensor.test_math
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/root/neon/nervanagpu/nervanagpu/tests/test_tensor.py", line 75, in test_math
    self.compare_helper('+', randA, randB, dtype)
  File "/root/neon/nervanagpu/nervanagpu/tests/test_tensor.py", line 55, in compare_helper
    nervanaGPU_result = self.math_helper(self.gpu, op, inA, inB, dtype=dtype)
  File "/root/neon/nervanagpu/nervanagpu/tests/test_tensor.py", line 28, in math_helper
    C[:] = A + B
  File "/root/neon/nervanagpu/nervanagpu/nervanagpu.py", line 391, in __setitem__
    self.__getitem__(index)._assign(value)
  File "/root/neon/nervanagpu/nervanagpu/nervanagpu.py", line 378, in _assign
    OpTreeNode.build("assign", self, value)
  File "/root/neon/nervanagpu/nervanagpu/nervanagpu.py", line 1229, in build
    return node.execute()
  File "/root/neon/nervanagpu/nervanagpu/nervanagpu.py", line 1242, in execute
    return call_compound_kernel(_get_rand_state(), *stack)
  File "/root/neon/nervanagpu/nervanagpu/float_ew.py", line 1065, in call_compound_kernel
    if arg in array_ids:
TypeError: unhashable type: 'GPUTensor'

----------------------------------------------------------------------
Ran 1 test in 0.028s

FAILED (errors=1)
```

**Comment by davidoj** [comment]
This seems to be a python 3 issue. I ran the test successfully in python 2, but I encountered the same error as this poster when I tried to run them in python 3.
