### ISSUE TITLE
error invoking 'nvcc --version': [Errno 2] No such file or directory ?

### ISSUE THREAD

**Issue by valexandersaulys** [NervanaSystems/nervanagpu#23]
I suppose this is more an issue with PyTools, but for the life of me I can't find any solution to it anywhere so I'm hoping somebody here can shed some light on my issue.

When I invoke one of the examples with the GPU as the backend, I get the error detailed below. I don't know why PyTools can't find my nvcc, which runs fine if I invoke that same command on the bash line. 

This leads me to think that perhaps PyTools is looking for the wrong path variable? Where could I set this? 

```
Traceback (most recent call last):
  File "mnist_mlp.py", line 126, in <module>
    mlp.fit(train_set, optimizer=optimizer, num_epochs=num_epochs, cost=cost, callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/models/model.py", line 149, in fit
    self._epoch_fit(dataset, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/models/model.py", line 167, in _epoch_fit
    for mb_idx, (x, t) in enumerate(dataset):
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/data/dataiterator.py", line 114, in __iter__
    xbuf[:, :bsz] = xdev[i1:i2].T
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/backends/nervanagpu.py", line 175, in __setitem__
    self.__getitem__(index)._assign(value)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/backends/nervanagpu.py", line 354, in _assign
    OpTreeNode.build("assign", self, value)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/backends/backend.py", line 1756, in build
    return node.execute()
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/backends/backend.py", line 1777, in execute
    return backend.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/backends/nervanagpu.py", line 974, in execute
    return call_compound_kernel(self._get_rand_state(), *stack)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/backends/float_ew.py", line 1388, in call_compound_kernel
    kernel = _get_compound_kernel(tuple(type_args))
  File "<string>", line 2, in _get_compound_kernel
  File "/usr/local/lib/python2.7/dist-packages/pycuda/tools.py", line 430, in context_dependent_memoize
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/backends/float_ew.py", line 1098, in _get_compound_kernel
    module = SourceModule(code, options=[])
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 259, in __init__
    arch, code, cache_dir, include_dirs)
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 249, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 84, in compile_plain
    checksum.update(get_nvcc_version(nvcc).encode("utf-8"))
  File "<string>", line 2, in get_nvcc_version
  File "/usr/lib/python2.7/dist-packages/pytools/__init__.py", line 425, in _deco
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 16, in get_nvcc_version
    result, stdout, stderr = call_capture_output(cmdline)
  File "/usr/lib/python2.7/dist-packages/pytools/prefork.py", line 196, in call_capture_output
    return forker[0].call_capture_output(cmdline, cwd, error_on_nonzero)
  File "/usr/lib/python2.7/dist-packages/pytools/prefork.py", line 53, in call_capture_output
    % ( " ".join(cmdline), e))
pytools.prefork.ExecError: error invoking 'nvcc --version': [Errno 2] No such file or directory
```

Below is what I get when I invoke "nvcc --version"
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```

Thanks in Advance!

**Comment by scttl** [comment]
nvcc usually resides in `/usr/local/cuda/bin` on a *nix OS (which is what I presume you are running).  You can confirm via a call to `which nvcc`.  So you'll want to make sure that directory is set in your `PATH` environment variable for the user you're trying to run the example as.  Issue an `echo $PATH` to confirm.

pycuda may also make use of the `CUDA_ROOT` variable so you may want to confirm whether or not that is set, and what value it is set to.

Beyond that you may want to  inject `import pdb; pdb.set_trace()` somewhere in that traceback and print the output of something like `os.getenv('PATH')` to see if that nvcc directory is in there.

**Comment by valexandersaulys** [comment]
I actually fixed this already. It had to do with how Ubuntu stores a separate $PATH variable for sudo as opposed to the regular user. Once I made the requisite changes to /etc/environment to add for /usr/local/cuda-7.5 it was all good. Thanks for replying quickly though!

**Comment by navekshasood** [comment]
Hey valexandersaulys,
I'm new to programming, and I am facing the same problem, can you take me step by step to what you did?

Thanks in advance!

**Comment by Jackerz312** [comment]
> Hey valexandersaulys,
> I'm new to programming, and I am facing the same problem, can you take me step by step to what you did?
> 
> Thanks in advance!

Hey, to solve that problem you need to use
sudo nautilus
then go to etc/enviroment (open that file)
and add :/usr/local/cuda-10.0/bin (use your version of cuda)
save it and u will have nvcc in your path
