### ISSUE TITLE
sudo make install not finding nvcc 

### ISSUE THREAD

**Issue by andreesteva** [NervanaSystems/nervanagpu#9]
when installing with the GPU=cudanet flag, 'sudo make install' raises the error 'nvcc not found'. It turns out that nvcc is not in the sudo path. I was able to fix this error by following the instructions here:
http://askubuntu.com/questions/428234/nvcc-not-found-but-only-when-using-sudo

Things seem to compile fine after that, however, the AlexNet model example does not work:
neon --gpu cudanet examples/convnet/i1k-alexnet-fp32.yaml

error:
2015-05-30 14:17:09,331 ERROR:imageset - Batch dir cache not found in /home/esteva/data/I1K/imageset_batches/dataset_cache.pkl:
Press Y to create, otherwise exit: Y
Traceback (most recent call last):
  File "/usr/local/bin/neon", line 240, in <module>
    experiment, result, status = main()
  File "/usr/local/bin/neon", line 208, in main
    result = experiment.run()
  File "/usr/local/lib/python2.7/dist-packages/neon/experiments/fit_predict_err.py", line 99, in run
    super(FitPredictErrorExperiment, self).run()
  File "/usr/local/lib/python2.7/dist-packages/neon/experiments/fit.py", line 73, in run
    self.dataset.load(backend=self.backend, experiment=self)
  File "/usr/local/lib/python2.7/dist-packages/neon/datasets/imageset.py", line 171, in load
    from neon.util.batch_writer import (BatchWriter,
  File "/usr/local/lib/python2.7/dist-packages/neon/util/batch_writer.py", line 25, in <module>
    import imgworker
ImportError: No module named imgworker

Whereas the CPU example does:
neon examples/mlp/mnist-small.yaml

**Comment by apark263** [comment]
Can you make sure that you've installed the imgworker module as well?

https://github.com/NervanaSystems/imgworker
